name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main # or master, whichever your default branch is

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Set up Git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create output branch if it doesn't exist
        run: |
          git checkout --orphan output || git checkout -b output
          git reset --hard

      - name: Commit and push snake.svg to the output branch
        run: |
          git add dist/snake.svg
          git commit -m "Add snake animation"
          git push origin output

      - name: Clean up orphan processes
        run: |
          pkill -f 'node'
          pkill -f 'python'
